import disassembler


class Microcontroller:
    def __init__(self):
        self._rom = ROM()
        self._pc = 0

    def __call__(self):
        while True:
            op = Operation(self._rom[self._pc])
            op.args = self._rom[self._pc + 1:self._pc + len(op)]
            self._pc += len(op)
            # Jump operations may override the PC
            exec(f'self.exec_{op.opcode}(*op.args)')

    def load_hex_file(self, filepath):
        for record in disassembler.IntelHexFile(filepath):
            for addr, byte in enumerate(record, record.first_byte_addr):
                self._rom[addr] = byte


class ROM:
    def __init__(self):
        self._data = [0] * 4000  # 4 KB

    def __getitem__(self, addr):
        return self._data[addr]

    def __setitem__(self, addr, value: int):
        self._data[addr] = value


class Operation:
    _opcodes = {
        0: {'length': 1, 'mnemonic': 'NOP'},
        1: {'length': 2, 'mnemonic': 'AJMP {:X}h'},
        2: {'length': 3, 'mnemonic': 'LJMP {:X}h'},
        3: {'length': 1, 'mnemonic': 'RR A'},
        4: {'length': 1, 'mnemonic': 'INC A'},
        5: {'length': 2, 'mnemonic': 'INC {:X}h'},
        6: {'length': 1, 'mnemonic': 'INC @R0'},
        7: {'length': 1, 'mnemonic': 'INC @R1'},
        8: {'length': 1, 'mnemonic': 'INC R0'},
        9: {'length': 1, 'mnemonic': 'INC R1'},
        10: {'length': 1, 'mnemonic': 'INC R2'},
        11: {'length': 1, 'mnemonic': 'INC R3'},
        12: {'length': 1, 'mnemonic': 'INC R4'},
        13: {'length': 1, 'mnemonic': 'INC R5'},
        14: {'length': 1, 'mnemonic': 'INC R6'},
        15: {'length': 1, 'mnemonic': 'INC R7'},
        16: {'length': 3, 'mnemonic': 'JBC {:X}h, {:X}h'},
        17: {'length': 2, 'mnemonic': 'ACALL {:X}h'},
        18: {'length': 3, 'mnemonic': 'LCALL {:X}h'},
        19: {'length': 1, 'mnemonic': 'RRC A'},
        20: {'length': 1, 'mnemonic': 'DEC A'},
        21: {'length': 2, 'mnemonic': 'DEC {:X}h'},
        22: {'length': 1, 'mnemonic': 'DEC @R0'},
        23: {'length': 1, 'mnemonic': 'DEC @R1'},
        24: {'length': 1, 'mnemonic': 'DEC R0'},
        25: {'length': 1, 'mnemonic': 'DEC R1'},
        26: {'length': 1, 'mnemonic': 'DEC R2'},
        27: {'length': 1, 'mnemonic': 'DEC R3'},
        28: {'length': 1, 'mnemonic': 'DEC R4'},
        29: {'length': 1, 'mnemonic': 'DEC R5'},
        30: {'length': 1, 'mnemonic': 'DEC R6'},
        31: {'length': 1, 'mnemonic': 'DEC R7'},
        32: {'length': 3, 'mnemonic': 'JB {:X}h, {:X}h'},
        33: {'length': 2, 'mnemonic': 'AJMP {:X}h'},
        34: {'length': 1, 'mnemonic': 'RET'},
        35: {'length': 1, 'mnemonic': 'RL A'},
        36: {'length': 2, 'mnemonic': 'ADD A, #{}'},
        37: {'length': 2, 'mnemonic': 'ADD A, {:X}h'},
        38: {'length': 1, 'mnemonic': 'ADD A, @R0'},
        39: {'length': 1, 'mnemonic': 'ADD A, @R1'},
        40: {'length': 1, 'mnemonic': 'ADD A, R0'},
        41: {'length': 1, 'mnemonic': 'ADD A, R1'},
        42: {'length': 1, 'mnemonic': 'ADD A, R2'},
        43: {'length': 1, 'mnemonic': 'ADD A, R3'},
        44: {'length': 1, 'mnemonic': 'ADD A, R4'},
        45: {'length': 1, 'mnemonic': 'ADD A, R5'},
        46: {'length': 1, 'mnemonic': 'ADD A, R6'},
        47: {'length': 1, 'mnemonic': 'ADD A, R7'},
        48: {'length': 3, 'mnemonic': 'JNB {:X}h, {:X}h'},
        49: {'length': 2, 'mnemonic': 'ACALL {:X}h'},
        50: {'length': 1, 'mnemonic': 'RETI'},
        51: {'length': 1, 'mnemonic': 'RLC A'},
        52: {'length': 2, 'mnemonic': 'ADDC A, #{}'},
        53: {'length': 2, 'mnemonic': 'ADDC A, {:X}h'},
        54: {'length': 1, 'mnemonic': 'ADDC A, @R0'},
        55: {'length': 1, 'mnemonic': 'ADDC A, @R1'},
        56: {'length': 1, 'mnemonic': 'ADDC A, R0'},
        57: {'length': 1, 'mnemonic': 'ADDC A, R1'},
        58: {'length': 1, 'mnemonic': 'ADDC A, R2'},
        59: {'length': 1, 'mnemonic': 'ADDC A, R3'},
        60: {'length': 1, 'mnemonic': 'ADDC A, R4'},
        61: {'length': 1, 'mnemonic': 'ADDC A, R5'},
        62: {'length': 1, 'mnemonic': 'ADDC A, R6'},
        63: {'length': 1, 'mnemonic': 'ADDC A, R7'},
        64: {'length': 2, 'mnemonic': 'JC {:X}h'},
        65: {'length': 2, 'mnemonic': 'AJMP {:X}h'},
        66: {'length': 2, 'mnemonic': 'ORL {:X}h, A'},
        67: {'length': 3, 'mnemonic': 'ORL {:X}h, #{}'},
        68: {'length': 2, 'mnemonic': 'ORL A, #{}'},
        69: {'length': 2, 'mnemonic': 'ORL A, {:X}h'},
        70: {'length': 1, 'mnemonic': 'ORL A, @R0'},
        71: {'length': 1, 'mnemonic': 'ORL A, @R1'},
        72: {'length': 1, 'mnemonic': 'ORL A, R0'},
        73: {'length': 1, 'mnemonic': 'ORL A, R1'},
        74: {'length': 1, 'mnemonic': 'ORL A, R2'},
        75: {'length': 1, 'mnemonic': 'ORL A, R3'},
        76: {'length': 1, 'mnemonic': 'ORL A, R4'},
        77: {'length': 1, 'mnemonic': 'ORL A, R5'},
        78: {'length': 1, 'mnemonic': 'ORL A, R6'},
        79: {'length': 1, 'mnemonic': 'ORL A, R7'},
        80: {'length': 2, 'mnemonic': 'JNC {:X}h'},
        81: {'length': 2, 'mnemonic': 'ACALL {:X}h'},
        82: {'length': 2, 'mnemonic': 'ANL {:X}h, A'},
        83: {'length': 3, 'mnemonic': 'ANL {:X}h, #{}'},
        84: {'length': 2, 'mnemonic': 'ANL A, #{}'},
        85: {'length': 2, 'mnemonic': 'ANL A, {:X}h'},
        86: {'length': 1, 'mnemonic': 'ANL A, @R0'},
        87: {'length': 1, 'mnemonic': 'ANL A, @R1'},
        88: {'length': 1, 'mnemonic': 'ANL A, R0'},
        89: {'length': 1, 'mnemonic': 'ANL A, R1'},
        90: {'length': 1, 'mnemonic': 'ANL A, R2'},
        91: {'length': 1, 'mnemonic': 'ANL A, R3'},
        92: {'length': 1, 'mnemonic': 'ANL A, R4'},
        93: {'length': 1, 'mnemonic': 'ANL A, R5'},
        94: {'length': 1, 'mnemonic': 'ANL A, R6'},
        95: {'length': 1, 'mnemonic': 'ANL A, R7'},
        96: {'length': 2, 'mnemonic': 'JZ {:X}h'},
        97: {'length': 2, 'mnemonic': 'AJMP {:X}h'},
        98: {'length': 2, 'mnemonic': 'XRL {:X}h, A'},
        99: {'length': 3, 'mnemonic': 'XRL {:X}h, #{}'},
        100: {'length': 2, 'mnemonic': 'XRL A, #{}'},
        101: {'length': 2, 'mnemonic': 'XRL A, {:X}h'},
        102: {'length': 1, 'mnemonic': 'XRL A, @R0'},
        103: {'length': 1, 'mnemonic': 'XRL A, @R1'},
        104: {'length': 1, 'mnemonic': 'XRL A, R0'},
        105: {'length': 1, 'mnemonic': 'XRL A, R1'},
        106: {'length': 1, 'mnemonic': 'XRL A, R2'},
        107: {'length': 1, 'mnemonic': 'XRL A, R3'},
        108: {'length': 1, 'mnemonic': 'XRL A, R4'},
        109: {'length': 1, 'mnemonic': 'XRL A, R5'},
        110: {'length': 1, 'mnemonic': 'XRL A, R6'},
        111: {'length': 1, 'mnemonic': 'XRL A, R7'},
        112: {'length': 2, 'mnemonic': 'JNZ {:X}h'},
        113: {'length': 2, 'mnemonic': 'ACALL {:X}h'},
        114: {'length': 2, 'mnemonic': 'ORL C, {:X}h'},
        115: {'length': 1, 'mnemonic': 'JMP @A+DPTR'},
        116: {'length': 2, 'mnemonic': 'MOV A, #{}'},
        117: {'length': 3, 'mnemonic': 'MOV {:X}h, #{}'},
        118: {'length': 2, 'mnemonic': 'MOV @R0, #{}'},
        119: {'length': 2, 'mnemonic': 'MOV @R1, #{}'},
        120: {'length': 2, 'mnemonic': 'MOV R0, #{}'},
        121: {'length': 2, 'mnemonic': 'MOV R1, #{}'},
        122: {'length': 2, 'mnemonic': 'MOV R2, #{}'},
        123: {'length': 2, 'mnemonic': 'MOV R3, #{}'},
        124: {'length': 2, 'mnemonic': 'MOV R4, #{}'},
        125: {'length': 2, 'mnemonic': 'MOV R5, #{}'},
        126: {'length': 2, 'mnemonic': 'MOV R6, #{}'},
        127: {'length': 2, 'mnemonic': 'MOV R7, #{}'},
        128: {'length': 2, 'mnemonic': 'SJMP {:X}h'},
        129: {'length': 2, 'mnemonic': 'AJMP {:X}h'},
        130: {'length': 2, 'mnemonic': 'ANL C, {:X}h'},
        131: {'length': 1, 'mnemonic': 'MOVC A, @A+PC'},
        132: {'length': 1, 'mnemonic': 'DIV AB'},
        133: {'length': 3, 'mnemonic': 'MOV {:X}h, {:X}h'},
        134: {'length': 2, 'mnemonic': 'MOV {:X}h, @R0'},
        135: {'length': 2, 'mnemonic': 'MOV {:X}h, @R1'},
        136: {'length': 2, 'mnemonic': 'MOV {:X}h, R0'},
        137: {'length': 2, 'mnemonic': 'MOV {:X}h, R1'},
        138: {'length': 2, 'mnemonic': 'MOV {:X}h, R2'},
        139: {'length': 2, 'mnemonic': 'MOV {:X}h, R3'},
        140: {'length': 2, 'mnemonic': 'MOV {:X}h, R4'},
        141: {'length': 2, 'mnemonic': 'MOV {:X}h, R5'},
        142: {'length': 2, 'mnemonic': 'MOV {:X}h, R6'},
        143: {'length': 2, 'mnemonic': 'MOV {:X}h, R7'},
        144: {'length': 3, 'mnemonic': 'MOV DPTR, #{}'},
        145: {'length': 2, 'mnemonic': 'ACALL {:X}h'},
        146: {'length': 2, 'mnemonic': 'MOV {:X}h, C'},
        147: {'length': 1, 'mnemonic': 'MOVC A, @A+DPTR'},
        148: {'length': 2, 'mnemonic': 'SUBB A, #{}'},
        149: {'length': 2, 'mnemonic': 'SUBB A, {:X}h'},
        150: {'length': 1, 'mnemonic': 'SUBB A, @R0'},
        151: {'length': 1, 'mnemonic': 'SUBB A, @R1'},
        152: {'length': 1, 'mnemonic': 'SUBB A, R0'},
        153: {'length': 1, 'mnemonic': 'SUBB A, R1'},
        154: {'length': 1, 'mnemonic': 'SUBB A, R2'},
        155: {'length': 1, 'mnemonic': 'SUBB A, R3'},
        156: {'length': 1, 'mnemonic': 'SUBB A, R4'},
        157: {'length': 1, 'mnemonic': 'SUBB A, R5'},
        158: {'length': 1, 'mnemonic': 'SUBB A, R6'},
        159: {'length': 1, 'mnemonic': 'SUBB A, R7'},
        160: {'length': 2, 'mnemonic': 'ORL C, /{:X}h'},
        161: {'length': 2, 'mnemonic': 'AJMP {:X}h'},
        162: {'length': 2, 'mnemonic': 'MOV C, {:X}h'},
        163: {'length': 1, 'mnemonic': 'INC DPTR'},
        164: {'length': 1, 'mnemonic': 'MUL AB'},
        165: {'length': 1, 'mnemonic': None},
        166: {'length': 2, 'mnemonic': 'MOV @R0, {:X}h'},
        167: {'length': 2, 'mnemonic': 'MOV @R1, {:X}h'},
        168: {'length': 2, 'mnemonic': 'MOV R0, {:X}h'},
        169: {'length': 2, 'mnemonic': 'MOV R1, {:X}h'},
        170: {'length': 2, 'mnemonic': 'MOV R2, {:X}h'},
        171: {'length': 2, 'mnemonic': 'MOV R3, {:X}h'},
        172: {'length': 2, 'mnemonic': 'MOV R4, {:X}h'},
        173: {'length': 2, 'mnemonic': 'MOV R5, {:X}h'},
        174: {'length': 2, 'mnemonic': 'MOV R6, {:X}h'},
        175: {'length': 2, 'mnemonic': 'MOV R7, {:X}h'},
        176: {'length': 2, 'mnemonic': 'ANL C, /{:X}h'},
        177: {'length': 2, 'mnemonic': 'ACALL {:X}h'},
        178: {'length': 2, 'mnemonic': 'CPL {:X}h'},
        179: {'length': 1, 'mnemonic': 'CPL C'},
        180: {'length': 3, 'mnemonic': 'CJNE A, #{}, {:X}h'},
        181: {'length': 3, 'mnemonic': 'CJNE A, {:X}h, {:X}h'},
        182: {'length': 3, 'mnemonic': 'CJNE @R0, #{}, {:X}h'},
        183: {'length': 3, 'mnemonic': 'CJNE @R1, #{}, {:X}h'},
        184: {'length': 3, 'mnemonic': 'CJNE R0, #{}, {:X}h'},
        185: {'length': 3, 'mnemonic': 'CJNE R1, #{}, {:X}h'},
        186: {'length': 3, 'mnemonic': 'CJNE R2, #{}, {:X}h'},
        187: {'length': 3, 'mnemonic': 'CJNE R3, #{}, {:X}h'},
        188: {'length': 3, 'mnemonic': 'CJNE R4, #{}, {:X}h'},
        189: {'length': 3, 'mnemonic': 'CJNE R5, #{}, {:X}h'},
        190: {'length': 3, 'mnemonic': 'CJNE R6, #{}, {:X}h'},
        191: {'length': 3, 'mnemonic': 'CJNE R7, #{}, {:X}h'},
        192: {'length': 2, 'mnemonic': 'PUSH {:X}h'},
        193: {'length': 2, 'mnemonic': 'AJMP {:X}h'},
        194: {'length': 2, 'mnemonic': 'CLR {:X}h'},
        195: {'length': 1, 'mnemonic': 'CLR C'},
        196: {'length': 1, 'mnemonic': 'SWAP A'},
        197: {'length': 2, 'mnemonic': 'XCH A, {:X}h'},
        198: {'length': 1, 'mnemonic': 'XCH A, @R0'},
        199: {'length': 1, 'mnemonic': 'XCH A, @R1'},
        200: {'length': 1, 'mnemonic': 'XCH A, R0'},
        201: {'length': 1, 'mnemonic': 'XCH A, R1'},
        202: {'length': 1, 'mnemonic': 'XCH A, R2'},
        203: {'length': 1, 'mnemonic': 'XCH A, R3'},
        204: {'length': 1, 'mnemonic': 'XCH A, R4'},
        205: {'length': 1, 'mnemonic': 'XCH A, R5'},
        206: {'length': 1, 'mnemonic': 'XCH A, R6'},
        207: {'length': 1, 'mnemonic': 'XCH A, R7'},
        208: {'length': 2, 'mnemonic': 'POP {:X}h'},
        209: {'length': 2, 'mnemonic': 'ACALL {:X}h'},
        210: {'length': 2, 'mnemonic': 'SETB {:X}h'},
        211: {'length': 1, 'mnemonic': 'SETB C'},
        212: {'length': 1, 'mnemonic': 'DA A'},
        213: {'length': 3, 'mnemonic': 'DJNZ {:X}h, {:X}h'},
        214: {'length': 1, 'mnemonic': 'XCHD A, @R0'},
        215: {'length': 1, 'mnemonic': 'XCHD A, @R1'},
        216: {'length': 2, 'mnemonic': 'DJNZ R0, {:X}h'},
        217: {'length': 2, 'mnemonic': 'DJNZ R1, {:X}h'},
        218: {'length': 2, 'mnemonic': 'DJNZ R2, {:X}h'},
        219: {'length': 2, 'mnemonic': 'DJNZ R3, {:X}h'},
        220: {'length': 2, 'mnemonic': 'DJNZ R4, {:X}h'},
        221: {'length': 2, 'mnemonic': 'DJNZ R5, {:X}h'},
        222: {'length': 2, 'mnemonic': 'DJNZ R6, {:X}h'},
        223: {'length': 2, 'mnemonic': 'DJNZ R7, {:X}h'},
        224: {'length': 1, 'mnemonic': 'MOVX A, @DPTR'},
        225: {'length': 2, 'mnemonic': 'AJMP {:X}h'},
        226: {'length': 1, 'mnemonic': 'MOVX A, @R0'},
        227: {'length': 1, 'mnemonic': 'MOVX A, @R1'},
        228: {'length': 1, 'mnemonic': 'CLR A'},
        229: {'length': 2, 'mnemonic': 'MOV A, {:X}h'},
        230: {'length': 1, 'mnemonic': 'MOV A, @R0'},
        231: {'length': 1, 'mnemonic': 'MOV A, @R1'},
        232: {'length': 1, 'mnemonic': 'MOV A, R0'},
        233: {'length': 1, 'mnemonic': 'MOV A, R1'},
        234: {'length': 1, 'mnemonic': 'MOV A, R2'},
        235: {'length': 1, 'mnemonic': 'MOV A, R3'},
        236: {'length': 1, 'mnemonic': 'MOV A, R4'},
        237: {'length': 1, 'mnemonic': 'MOV A, R5'},
        238: {'length': 1, 'mnemonic': 'MOV A, R6'},
        239: {'length': 1, 'mnemonic': 'MOV A, R7'},
        240: {'length': 1, 'mnemonic': 'MOVX @DPTR, A'},
        241: {'length': 2, 'mnemonic': 'ACALL {:X}h'},
        242: {'length': 1, 'mnemonic': 'MOVX @R0, A'},
        243: {'length': 1, 'mnemonic': 'MOVX @R1, A'},
        244: {'length': 1, 'mnemonic': 'CPL A'},
        245: {'length': 2, 'mnemonic': 'MOV {:X}h, A'},
        246: {'length': 1, 'mnemonic': 'MOV @R0, A'},
        247: {'length': 1, 'mnemonic': 'MOV @R1, A'},
        248: {'length': 1, 'mnemonic': 'MOV R0, A'},
        249: {'length': 1, 'mnemonic': 'MOV R1, A'},
        250: {'length': 1, 'mnemonic': 'MOV R2, A'},
        251: {'length': 1, 'mnemonic': 'MOV R3, A'},
        252: {'length': 1, 'mnemonic': 'MOV R4, A'},
        253: {'length': 1, 'mnemonic': 'MOV R5, A'},
        254: {'length': 1, 'mnemonic': 'MOV R6, A'},
        255: {'length': 1, 'mnemonic': 'MOV R7, A'}
    }

    def __init__(self, opcode: int, *args: int):
        self.opcode = opcode
        self.args = args

    def __len__(self):
        return self._opcodes[self.opcode]['length']

    def __str__(self):
        # Turn two one-byte arguments (as stored in a .hex file) into one two-byte argument
        # e.g. 0xAB = 171, 0xCD = 205; 171 * 16 ** 2 + 205 = 43981 = 0xABCD
        args = [self.args[0] * 16 ** 2 + self.args[1]] if self.opcode in (2, 18, 144) else self.args
        return self._opcodes[self.opcode]['mnemonic'].format(*args)
